local armorDefs = {
	air = {
		"armawac",
		"armthund",
		"armbrawl",
		"armpeep",
		"armfig",
		"armca",
		"armatlas",
		"armpnix",
		"armhawk",
		"armlance",
		"blade",
		"armtoad",
		"armwing",
		"armhell",
		"cmercdrag",
		"armsehak",
		"armsfig",
		"armseap",
		"armangel",
		"armkam",
		
		"corfink",
		"corveng",
		"corvamp",
		"corhurc",
		"cortitan",
		"corshad",
		"corape",
		"corca",
		"corvalk",
		"corevashp",
		"corsfig",
		"corbrik",
		"armsl",
		"corhunt",
		"corseap",
		"corerb",
		"corawac",
		"corsbomb",
		"corgryp",
		"corbtrans",
		"corvalkii",
		"cordcarry",
		
		"bladewing",
	},
	bugair = {
		"corgamma",
		"corgamma2",
		"armserp",
	},
	flyingfortress = {
		"corff",
	},
	heavy = {
		"corsumo",
		"corgol",
		"correap",
		"corcrabe",
		"corcan",
		"armbull",
		"armpug",
		"herfatboy",
		"herstalwart",
		"herjuggernaut",
		"corcom",
		"corcom2",
	},
	bugheavy = {
		"bug3",
	},
	bugair = {
		"corgamma",
	},
	bugmedium = {
		"bug4",
		"bug5",
		"wormy",
		"cormonsta",
		"cormonstaq",
	},
	buglight = {
		"bug1",
		"bug2",
		"cormonstab",
	},
	medium = {
		"corraid",
		"corseal",
		"corhorg",
		"corsent",
		"armstump",
		"armodd",
		"armcroc",
		"raptoriv",
		"madcat",
		"armdrake",
		"grayhound",
		"corgala",
		"armpod",
		"armcom",
		"armcom2",
		"armbcom",
		"corhktank",
		"corkrog",
		"coramph",
		"corfatnk",
		"armflash",
		"corgator",
		"armlatnk",
		"hertrapper",
		"hermarksman",
		"herpivot",
		"hercleaver",
		"hersabo",
		"armzeus",
		"corpyro",
	},
	mines = {
		"armmine1",
		"armmine2",
		"armmine3",
		"armmine4",
		"armmine5",
		"armmine6",
		"cormine1",
		"cormine2",
		"cormine3",
		"cormine4",
		"cormine5",
		"cormine6",
		"cormine7",
	},
	light = {
		"armajam",
		"armaser",
		"armck",
		"armcv",
		"armfark",
		"armfast",
		"armfav",
		"armham",
		"armjam",
		"armjeth",
		"armmanni",
		"armmark",
		"armmart",
		"armmav",
		"armmerl",
		"armpw",
		"armrock",
		"armsam",
		"armscab",
		"armseer",
		"armsnipe",
		"armspid",
		"armspy",
		"armship",
		"armyork",
		"ahermes",
		"pitviper",
		"armflea",
		"corajam",
		"corack",
		"corak",
		"corck",
		"corcrash",
		"corcv",
		"coreter",
		"corfast",
		"corfav",
		"corhrk",
		"corlevlr",
		"cormabm",
		"cormart",
		"cormist",
		"cormort",
		"cornecro",
		"corspec",
		"corspy",
		"corstorm",
		"corthud",
		"cortruck",
		"corvoyr",
		"corvrad",
		"corvroc",
		"cougar",
		"armfido",
		"sprint",
		"armray",
		"cortraq",
		"corsabo",
		"armwar",
		"cormak",
		"armdrone",
	},
	ships = {
		"armexcal",
		"armexcal2",
		"armewar",
		"armcrus",
		"armaacrus",
		"armmcrus",
		"armbcrus",
		"aseadragon",
		"armcarry",
		
		"cordest",
		"cormblade",
		"corewar",
		"m-blade",
		"corcrus",
		"coraacrus",
		"corbcrus",
		"corhmcrus",
		"corblackhy",
		"coraat",
		"corcarry",
	},
	subs = {
		"corsub",
		"armacsub",
		"coracsub",
		"armtib",
	},
	hovertank = {
		"armanac",
		"corsnap",
		"armthovr",
		"corthovr",
		"armsh",
		"corsh",
		"armmh",
		"cormh",
		"armah",
		"corah",
		"armch",
		"corch",
		"armamph",
		"corasubh",
		"armasubh",
		"armhover3g",
	},
	base = {
		"corbase",
		"armbase",
	},
	crawlingbomb = {
		"corroach",
		"armvader",
	},
	roost = {
		"roost",
		"chickend",
	},
	scram = {
		"scramerunit",
		"emperunit",
	},
}

-- just fix to make it work for older engines (before 95) and 95+ newer
local oldStyle = true
if (Game ~= nil and ((tonumber(Game.version) or 96) >= 95)) then
	oldStyle = false
end

-- this convert subtables from list of strings to hast tables "string" -> 99
local oldArmors = {}
if (oldStyle) then
	for k,v in pairs(armorDefs) do
		oldArmors[k] = {}
		local subtableForConvertion = v
		
		for i=1,#subtableForConvertion do
			local unitName = subtableForConvertion[i]
			oldArmors[k][unitName] = 99
		end
	end
	
	return oldArmors
end
-- end of fix

return armorDefs
