----- mission groups settigns ------
----- more about: http://springrts.com/phpbb/viewtopic.php?f=55&t=28259

newGroupDef = {
    ["peeweeGroup1"] = {size = 20, unit = "armpw", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["peeweeGroup2"] = {size = 20, unit = "armpw", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["peeweeGroup3"] = {size = 20, unit = "armpw", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["peeweeGroup4"] = {size = 20, unit = "armpw", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["peeweeGroup5"] = {size = 20, unit = "armpw", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["peeweeGroup6"] = {size = 20, unit = "armpw", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["peeweeGroup7"] = {size = 20, unit = "armpw", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["peeweeGroup8"] = {size = 20, unit = "armpw", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["peeweeGroup9"] = {size = 20, unit = "armpw", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["peeweeGroup10"] = {size = 20, unit = "armpw", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["peeweeGroup11"] = {size = 20, unit = "armpw", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["peeweeGroup12"] = {size = 20, unit = "armpw", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["hammerGroup1"] = {size = 20, unit = "armham", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["hammerGroup2"] = {size = 20, unit = "armham", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["hammerGroup3"] = {size = 20, unit = "armham", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["hammerGroup4"] = {size = 20, unit = "armham", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["hammerGroup5"] = {size = 20, unit = "armham", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["hammerGroup6"] = {size = 20, unit = "armham", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["rockoGroup1"] = {size = 20, unit = "armrock", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["rockoGroup2"] = {size = 20, unit = "armrock", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["rockoGroup3"] = {size = 20, unit = "armrock", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["rockoGroup4"] = {size = 20, unit = "armrock", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["rockoGroup5"] = {size = 20, unit = "armrock", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["rockoGroup6"] = {size = 20, unit = "armrock", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},
	["bulldogGang1"] = {size = 10, unit = "armbull", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Veh1", dependance = false},
	["bulldogGang2"] = {size = 10, unit = "armbull", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Veh1", dependance = false},
	["bulldogGang3"] = {size = 10, unit = "armbull", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Veh1", dependance = false},
	["bulldogGang4"] = {size = 10, unit = "armbull", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Veh1", dependance = false},
	["bulldogGang5"] = {size = 10, unit = "armbull", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Veh1", dependance = false},
	["bulldogGang6"] = {size = 10, unit = "armbull", spirit = "angryRaid", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Veh1", dependance = false},
	["transportFleet"] = {size = 7, unit = "coraat", spirit = "spawnLeader", transfer = 1, status = {0,1,2,3}, preference = {1,2,3,4,5,6,7}, targetClasses = {"metal","defWeapons"}, source = "Bot1", dependance = false},	
}