----- mission spawn list ------
----- more about: http://springrts.com/phpbb/viewtopic.php?f=55&t=28259

newSpawnDef = {
    ["t-dca"]       = {unit = "dca", class = "single"},
    ["t-corak"]       = {unit = "corak", class = "single"},
    ["t-cormine2"]       = {unit = "cormine2", class = "single"},
    ["t-cormine3"]       = {unit = "cormine3", class = "single"},
    ["t-corstorm"]       = {unit = "corstorm", class = "single"},
    ["t-corpun"]       = {unit = "corpun", class = "single"},
    ["t-corplas"]       = {unit = "corplas", class = "single"},
    ["t-cormort"]       = {unit = "cormort", class = "single"},
    ["t-cornecro"]       = {unit = "cornecro", class = "single"},
    ["t-corwin"]       = {unit = "corwin", class = "single"},
    ["t-corthud"]       = {unit = "corthud", class = "single"},
    ["t-corfus"]       = {unit = "corfus", class = "single"},
    ["t-corfury"]       = {unit = "corfury", class = "single"},
    ["t-corasp"]       = {unit = "corasp", class = "single"},
    ["t-corestor"]       = {unit = "corestor", class = "single"},
    ["t-corrad"]       = {unit = "corrad", class = "single"},
    ["t-corcom2"]       = {unit = "corcom2", class = "single"},
    ["t-corvipe"]       = {unit = "corvipe", class = "single"},
    ["t-corsupergun"]       = {unit = "corsupergun", class = "single"},
    ["t-shika"]       = {unit = "shika", class = "single"},
    ["t-corlab"]       = {unit = "corlab", class = "single"},
    ["t-corsolar"]       = {unit = "corsolar", class = "single"},
    ["t-corvoyr"]       = {unit = "corvoyr", class = "single"},
    ["t-armcom2"]       = {unit = "herpivot", class = "single"},
}

newSpawnThis = {
    {name = "t-dca", posX = 4320, posZ = 7440, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 3968, posZ = 5040, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 5232, posZ = 4784, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corak", posX = 2526.3515625, posZ = 6158.388671875, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 5032, posZ = 6872, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corak", posX = 2556.0021972656, posZ = 6163.8408203125, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 5080, posZ = 6600, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5240, posZ = 3896, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4952, posZ = 7000, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5320, posZ = 3960, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corak", posX = 4487.7592773438, posZ = 7308.7270507813, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corstorm", posX = 4238.1845703125, posZ = 7413.673828125, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4664, posZ = 7576, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corpun", posX = 4065, posZ = 4078, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 3792, posZ = 7296, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corplas", posX = 4918, posZ = 4468, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormort", posX = 4432.7358398438, posZ = 5575.3227539063, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4824, posZ = 6744, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 4096, posZ = 4560, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5224, posZ = 3704, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cornecro", posX = 2976, posZ = 6451, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4600, posZ = 6696, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4952, posZ = 6664, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corak", posX = 2658.1469726563, posZ = 6036.4965820313, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4472, posZ = 6776, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corwin", posX = 1408, posZ = 5664, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5288, posZ = 3800, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corthud", posX = 4089.9855957031, posZ = 7394.36328125, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 5032, posZ = 7000, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4824, posZ = 7560, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5160, posZ = 3960, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4456, posZ = 6696, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4792, posZ = 6648, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormort", posX = 4404.556640625, posZ = 5779.8784179688, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4904, posZ = 6888, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormort", posX = 4121.1376953125, posZ = 6425.3349609375, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corak", posX = 4360.8500976563, posZ = 7226.5795898438, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 4208, posZ = 5904, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corfus", posX = 2792, posZ = 5368, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corfury", posX = 4576, posZ = 7120, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 5312, posZ = 5040, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corasp", posX = 4988, posZ = 4240, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corestor", posX = 2720, posZ = 5200, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4952, posZ = 7736, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5160, posZ = 3960, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormort", posX = 4159.197265625, posZ = 7223.1586914063, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corestor", posX = 2624, posZ = 5296, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4696, posZ = 6712, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4584, posZ = 6808, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corestor", posX = 2960, posZ = 5344, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4952, posZ = 7496, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 4464, posZ = 7344, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corstorm", posX = 4247.5341796875, posZ = 7258.2485351563, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corasp", posX = 3856, posZ = 7504, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corak", posX = 4533.6352539063, posZ = 7242.8110351563, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 4320, posZ = 5776, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormort", posX = 4243.4467773438, posZ = 6374.052734375, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5320, posZ = 3960, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5128, posZ = 4040, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormort", posX = 4105.9018554688, posZ = 7043.689453125, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corwin", posX = 1488, posZ = 5840, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 4768, posZ = 4272, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corak", posX = 2545.9233398438, posZ = 6113.5581054688, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4808, posZ = 6856, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corwin", posX = 1472, posZ = 5760, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 4720, posZ = 4464, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 5080, posZ = 6696, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corfury", posX = 4272, posZ = 6480.638671875, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corpun", posX = 3611, posZ = 8053, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormort", posX = 4481.326171875, posZ = 5716.5478515625, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 4512, posZ = 5680, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4936, posZ = 7608, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5160, posZ = 3864, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4776, posZ = 7736, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormort", posX = 4123.216796875, posZ = 7060.052734375, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5080, posZ = 3928, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corfury", posX = 5008, posZ = 4129.6928710938, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 5056, posZ = 4576, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corrad", posX = 3904, posZ = 7232, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corcom2", posX = 3124.1083984375, posZ = 7623.4135742188, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corvipe", posX = 4144, posZ = 7904, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormort", posX = 4164.0659179688, posZ = 6405.1381835938, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4968, posZ = 6776, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5320, posZ = 3752, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5224, posZ = 3704, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corwin", posX = 1376, posZ = 5536, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corestor", posX = 2512, posZ = 5792, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corsupergun", posX = 2616, posZ = 5480, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corwin", posX = 1456, posZ = 5920, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4552, posZ = 7656, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5080, posZ = 3928, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 4256, posZ = 5472, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corak", posX = 4402.31640625, posZ = 7146.8813476563, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4664, posZ = 6600, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corak", posX = 2557.3754882813, posZ = 6085.6040039063, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 4032, posZ = 5360, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 4080, posZ = 6064, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corestor", posX = 2832, posZ = 5760, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormort", posX = 4508.4130859375, posZ = 5622.5297851563, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corthud", posX = 4083.4243164063, posZ = 7483.8237304688, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 4192, posZ = 6992, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corak", posX = 2505.5642089844, posZ = 5994.857421875, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5128, posZ = 4040, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 5024, posZ = 4384, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5288, posZ = 3800, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5240, posZ = 3896, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corthud", posX = 4093.0832519531, posZ = 7346.9350585938, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-shika", posX = 4009, posZ = 6681, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corasp", posX = 4878, posZ = 4370, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corlab", posX = 2624, posZ = 5856, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corsolar", posX = 2713, posZ = 6203, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corvipe", posX = 4416, posZ = 7984, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormort", posX = 4199.1865234375, posZ = 6392.4453125, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5160, posZ = 3864, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4584, posZ = 7528, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4504, posZ = 6632, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5400, posZ = 3912, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corestor", posX = 2736, posZ = 5840, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4984, posZ = 7224, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corfury", posX = 4309.5395507813, posZ = 7267.3857421875, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corthud", posX = 4087.8562011719, posZ = 7444.701171875, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corak", posX = 2677.8227539063, posZ = 6140.693359375, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corfury", posX = 4368, posZ = 7024.0249023438, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 4912, posZ = 4160, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5400, posZ = 3912, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corasp", posX = 4312, posZ = 8040, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4696, posZ = 6856, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corwin", posX = 1552, posZ = 6000, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4952, posZ = 6552, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4856, posZ = 6936, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormort", posX = 4081.6745605469, posZ = 6439.9296875, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corvoyr", posX = 4389.7084960938, posZ = 5536.4633789063, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dca", posX = 4864, posZ = 4528, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4616, posZ = 6904, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corfus", posX = 2664, posZ = 5688, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corestor", posX = 2480, posZ = 5680, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corestor", posX = 2864, posZ = 5200, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine2", posX = 4824, posZ = 7656, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormort", posX = 3962.0629882813, posZ = 7029.8999023438, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-cormine3", posX = 5320, posZ = 3752, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corvipe", posX = 3968, posZ = 7488, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-armcom2", posX = 8030, posZ = 7820, facing = "n", teamName = "player1", checkType = "none", gameTime = 0},
}
newSpawnFeatureDef = {
    ["t-dragonsteeth_core"]       = {unit = "dragonsteeth_core", class = "feature"},
    ["t-geovent"]       = {unit = "geovent", class = "feature"},
    ["t-cordest_dead"]       = {unit = "cordest_dead", class = "feature"},
    ["t-corthovr_dead"]       = {unit = "corthovr_dead", class = "feature"},
}

newFeaturesSpawn = {
    {name = "t-dragonsteeth_core", posX = 5432, posZ = 5064, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 5432, posZ = 5016, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 5416, posZ = 4968, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-geovent", posX = 2620, posZ = 5484, facing = "s", teamName = "player-1", checkType = "none", gameTime = 0},
    {name = "t-geovent", posX = 5868, posZ = 5764, facing = "s", teamName = "player-1", checkType = "none", gameTime = 0},
    {name = "t-cordest_dead", posX = 6617.4790039063, posZ = 4296.5810546875, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 5000, posZ = 7752, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4856, posZ = 6712, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4872, posZ = 7048, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4712, posZ = 7528, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4855.9526367188, posZ = 7496.0473632813, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4968.029296875, posZ = 6919.9995117188, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4968, posZ = 6600, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4312, posZ = 6664, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4408, posZ = 6904, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4952, posZ = 7672, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4759.9521484375, posZ = 6679.9702148438, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4824, posZ = 6904, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4744, posZ = 6616, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 5000, posZ = 6776, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4312, posZ = 6824, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4904, posZ = 6984, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4424, posZ = 6840, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4599.96875, posZ = 7591.9760742188, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4696, posZ = 7704, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4744, posZ = 6904, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 5368, posZ = 5128, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4872, posZ = 7160, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4296, posZ = 6712, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4856, posZ = 7752, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 5400, posZ = 5112, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4840, posZ = 7000, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4792, posZ = 6936, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4936, posZ = 6840, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4823.91796875, posZ = 6663.7529296875, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4424, posZ = 6664, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 5288, posZ = 5112, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4631.9438476563, posZ = 6744.0297851563, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4680, posZ = 6904, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4296, posZ = 6904, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 5032.0063476563, posZ = 6664.0078125, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4760.0009765625, posZ = 7623.9951171875, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corthovr_dead", posX = 6285.046875, posZ = 4429.9887695313, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 5016, posZ = 6600, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4984, posZ = 7096, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4920, posZ = 6952, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4568, posZ = 6920, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4984, posZ = 6840, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4936, posZ = 6536, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4856, posZ = 6872, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4872, posZ = 6840, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 5032, posZ = 6728, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4488, posZ = 7640, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4888, posZ = 7192, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4888, posZ = 7640, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4872, posZ = 6600, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4616, posZ = 7720, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4679.9028320313, posZ = 6792.0356445313, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4984, posZ = 7464, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4888, posZ = 7560, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4760, posZ = 6760, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4504, posZ = 6696, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4360, posZ = 6936, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4904, posZ = 6728, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4520, posZ = 6728, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-corthovr_dead", posX = 6974.6918945313, posZ = 4217.9877929688, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 5320, posZ = 5128, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4648, posZ = 6696, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4631.9545898438, posZ = 6775.9526367188, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4520, posZ = 7544, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4552, posZ = 6760, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4760, posZ = 7512, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4760, posZ = 6872, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4712, posZ = 7768, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4360, posZ = 6760, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4424.0317382813, posZ = 6759.951171875, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4728, posZ = 6664, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4408, posZ = 6696, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4696, posZ = 7624, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4935.9565429688, posZ = 7063.9775390625, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4968, posZ = 7160, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4984, posZ = 7576, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
    {name = "t-dragonsteeth_core", posX = 4520, posZ = 6824, facing = "s", teamName = "pino-base", checkType = "none", gameTime = 0},
}


function NewSpawner()
    --Spring.Echo("N.O.E. mission_spawner: mission spawner works, but its empty")
end